### ISSUE TITLE
Blocking Main Thread

### ISSUE THREAD

**Issue by DominikTrenz** [metafloor/bwip-js#67] opened 2017-03-01 03:00 UTC
My use case:
I'm generating a "datamatrix" code near to the max size (6x6 matrix) and i'm using the node module's "toBuffer" method.

Problem:
The generating of the png takes ~30-40 seconds and the main thread is blocked.

Solution:
Is it maybe possible to stream the bytes in an async way?

**Comment by metafloor** [comment] 2017-03-01 05:11
Please provide an example of the parameters you are using.  I will profile the code to determine where the time is being spent.

**Comment by DominikTrenz** [comment] 2017-03-02 01:54
```
var data ='<MP v="023" U="4AF24B4303BD4261B3E9BB53370D3898" a="1" z="2" l="de-DE"><P g="Erika-Annemarie" f="Maxdata-Demonstration" egk="P123456789" b="1964-10-19"/><A n="Apotheke Winfried Wagenmüller" s="Hauptstraße 55" z="99900" c="Furth am Wald" p="098765-12345678" e="Wagenmueller.apotheke@medizin-netz.de" t="2016-07-15"/><O ai="Katzenhaare" w="125"/><S><M p="55509" m="1" d="1" v="1" du="5" i="kompletter Sprühstoß" r="Heuschnupfen"/><M p="2340148" m="1/4" d="1/4" v="1/4" du="1" i="in 1 Glas Wasser lösen" r="Osteoporose"/><M p="7381821" m="1" du="1" i="nach der Mahlzeit" r="hoher Blutdruck"/><M f="SUS" t="alle 8 Stunden 1" du="#" i="max. 3 Tage (1 Messlöffel=5ml)" r="Harnwegsinfekt"><W w="Trimethoprim\Sulfamethoxazol"/></M><M f="TAB" m="1/2" d="1/2" v="1/2" du="1" i="bitte an die Zeiten halten" r="Blutdruck"><W w="Amlodipin (Besilat)" s="10 mg"/><W w="Hydrochlorothiazid" s="25 mg"/><W w="Olmesartan Medoxomil" s="40 mg"/></M><M f="PUL" du="8" i="Dosierung war nicht bekannt" r="Magen-Darm Beschw."><W w="Ein-neuer2Wirkstoff" s="10 mg"/></M><M a="Omcilon-A Orabase" fd="Mundcre" m="1" d="1" v="1" h="1" du="q" i="in Brasilien erworben" r="Mundbläschen"><W w="Acetonido de Triancinolona" s="1 mg/g"/></M><R t="Hautsalbe (Polidocanol-600-Zinkoxidschüttelmixtur 5% 2x täglich auf Handflächen (mo. &amp; ab. Nach Händewaschen) schuppiges Exanthem"/></S></MP>';
toBuffer({
    bcid: 'datamatrix', // Barcode type
    text: data,
    scale: 10
}, ...
```

**Comment by metafloor** [comment] 2017-03-02 17:04
The bad news is the profiling shows this is a javascript performance issue.  Completely CPU bound and will require a major change in architecture to alleviate.  

So my recommendations for the time being:
- Do you really need `scale=10` for your images?  That is the equivalent of 720dpi.  My production applications use 'scale=3` and `scale=4` when printing to 600dpi printers with no loss of image crispness.
- Even with reduced scale, rendering will take some seconds, completely CPU bound.  If you need absolute responsiveness from node, I recommend you configure a node cluster dedicated to just rendering these large-format bar codes.  From your primary node instance, reverse proxy the bar code requests to this cluster.

I have used the reverse-proxy architecture for doing other CPU-bound and/or synchronous-only tasks with node and it works well.

One thing I will investigate in the next few weeks is offloading the entire bar code rendering process to a web-worker style thread.  My concern here is that the emscripten-compiled freetype library makes certain assumptions about its runtime environment and I am not sure how it will react.

**Comment by DominikTrenz** [comment] 2017-03-03 05:11
Thanks for investigating this. Maybe i can go down with the scale a bit, i will test it later. A node cluster won't work for my setup, but i'm a big fan of the web-worker idea.

**Comment by metafloor** [comment] 2017-04-03 00:50
Just an update on this topic.  I have nixed the web-workers idea.  Too complicated and brings in native code dependencies.

After some more profiling of the code, a better design has emerged that will benefit both browser-based and node-based rendering.  The original two-pass image drawing (the Bitmap interface) was designed when the translated postscript code was the limiting factor; it was really slow.  With the optimized postscript execution, the Bitmap interface has become the bottleneck.

The rather obvious solution is to run the postscript code twice, rather than the image rendering.  The first pass will simply determine the min/max extents of the image; this will be really fast (tens of milliseconds for large images; barely noticeable for smaller).  The second pass will draw the image directly into a node Buffer in PNG format or an HTML canvas bitmap, including any necessary x,y translations and rotations.

This will be an API-breaking change (just at the Bitmap interface), but for the better.  Most people use bwip-js "as is" and will not be impacted.  And especially for the node users, this should dramatically decrease GC pressure and CPU usage, and improve responsiveness. 

For anyone receiving these notices, if you have concerns about this change and how it will impact your deployments, please let me know.  I am buried with work right now and will not be implementing this for at least a month.

**Comment by skumar568** [comment] 2017-05-12 07:06
Could you please confirm if above fix is available in latest version of module (1.3.2)?

**Comment by metafloor** [comment] 2017-05-12 13:16
Not available yet.  My local development branch has the new code and the results are encouraging.  With the example provided by @DominikTrenz, the current 1.3.2 code runs about 18-20 seconds on my laptop.  With the new code, it runs 0.8 - 1.2 seconds.  The main thread is still blocked during that time, but a worthy improvement, none the less.  There is also significant reduction on GC pressure, as "point/color" objects are no longer being created.  Large symbols could create 5M - 10M objects previously.

I am hoping there will be time next week to wrap up the testing and documentation for a release.  It will be version 1.4 when available.

**Comment by terryburton** [comment] 2017-05-12 13:42
> The rather obvious solution is to run the postscript code twice, rather than the image rendering. The first pass will simply determine the min/max extents of the image; this will be really fast (tens of milliseconds for large images; barely noticeable for smaller). The second pass will draw the image directly into a node Buffer in PNG format or an HTML canvas bitmap, including any necessary x,y translations and rotations.

I wrote this yesterday and just noticed that GitHub blackholed the email...

Would it be helpful if I were to add an emitbbox option up the PostScript that calculates the bbox and sends this to stdout or leaves the values on the PS stack? Would this avoid multipass by making it simple to crop the resulting image, or are you seeking to size the canvas appropriately up front to entirely avoid cropping?

**Comment by metafloor** [comment] 2017-05-12 15:20
I too thought that calculating a bounding box might be useful and even implemented it inside the three renderers.  I found that it was too expensive to re-calculate the bar code data, especially for data intensive 2d symbols with high levels of EC.  So an `emitbox` option would be valuable only if you push both the bounding box and the full bar code data onto the stack, allowing the renderers to run later against the already calculated data.  That was beyond my feeble PostScript abilities....

Fortunately, the profiling revealed some major performance bottlenecks in other parts of the bwip-js image generation, so this is where I focused the new development.  By eliminating one backend rendering pass and eliminating tons of object creation, the code now runs faster for both big and small images.

**Comment by metafloor** [comment] 2017-05-12 15:33
Just a follow up to the above as my comment starting wandering.  Please consider adding an `emitbox` option - it would allow drawing directly into the PNG file format.  I don't know if it would improve response time for bwip-js, but it would definitely further reduce GC pressure for large images.

**Comment by terryburton** [comment] 2017-05-12 15:50
I'll take a look. It requires a little bit of internal reorganisation to change the behaviour of the dontdraw option to mute the graphical actions within the renderers themselves (which would calculate their bbox) rather than simply not call them as happens at present.

We would also have to take care to merge the bboxes of "composite-style" symbologies which invoke multiple renderers or the same renderer multiple times.

When I work on it I'll update [here](https://github.com/bwipp/postscriptbarcode/issues/85).

**Comment by metafloor** [comment] 2017-05-12 16:46
It might be easier to only put the emitbox logic in the renderers and add the bbox as a property of the bar code data, which is left on the stack.  A front end can extract the bbox from each stack entry and more easily merge the boxes rather than have BWIPP do it.  

Especially for composite symbols, that should greatly simplify the BWIPP code.

Now that I am talking this through, I see where I went wrong with my attempted implementation.  I may give this a try next week ;-)

**Comment by skumar568** [comment] 2017-05-13 13:25
Would it be possible to share your branch where above fix is available?

**Comment by metafloor** [comment] 2017-05-24 21:10
I am swamped with work right now and do not have time to finalize this release.  Therefore, I have pushed the changes to the develop branch.  You will need to copy the following files to your local `bwip-js/` directory:

```
bwipp.js
bwipjs.js
node-bwipjs.js
node-bitmap.js
```
`node-bitmap.js` is a merge of the Bitmap class defined in the old `node-bwipjs.js` and `node-zlibPNG.js` modules.  This code is still requires two passes to create the PNG but it has been highly optimized.  The timing numbers I reported above should be achievable with it.

The code is passing all "content" tests but many of the image comparison tests are failing because the new code is selecting different PNG formats and alpha values.  I need time to validate these failures and update the image proofs.  I have not seen anything to indicate the code is not production ready but please test with 2d scanners to be certain.

**Comment by metafloor** [comment] 2017-07-12 23:01
Release 1.4.1 is out with the performance enhancements.  Based on current profiling, there may still be minor gains to be had with the image rendering but they will be hard fought.  For now, 1.4 is the last of the development for resolving this issue.  The next focus will be getting rid of freetype.

**Comment by metafloor** [comment] 2017-09-01 21:22
Version 1.5 is out that may improve the performance you see with large symbols.  Please let me know how it works for you.

**Comment by metafloor** [comment] 2017-09-13 17:09
Closing as resolved.  Version 1.5 has squeezed out as much buffer writing optimization as possible.

**Closed by metafloor** 2017-09-13 17:09 UTC
