### ISSUE TITLE
New "not a realtype/booleantype" errors from 2.0.11 to 3.2.1

### ISSUE THREAD

**Issue by semireg** [metafloor/bwip-js#277] opened 2022-12-10 20:40 UTC
Hi,

When I upgrade from 3.2.1 some previously working options now produce an error. I want to make sure that this new behavior is intentional, or if I'm seeing a regression in 3.2.1.

Here are two examples:

DataMatrix
```
bwipp.invalidOptionType: columns: not a realtype: undefined options:{
   "bcid": "datamatrix",
   "scale": 2,
   "rotate": "N",
   "text": "This is Data Matrix!",
   "barcolor": "000000",
   "textcolor": "000000",
   "parse": false
}
```

[Docs](https://github.com/bwipp/postscriptbarcode/wiki/GS1-DataMatrix) say `If columns, rows and version are unspecified the encoder will default to creating a symbol of the specified format that is the minimum size to represent the given data.`

QR code
```
bwipp.invalidOptionType: includetext: not a booleantype: undefined options:{
   "bcid": "qrcode",
   "scale": 6,
   "rotate": "N",
   "text": "Empty",
   "barcolor": "000000",
   "textcolor": "000000",
   "eclevel": "M",
   "parse": false
}
```

[Docs](https://github.com/bwipp/postscriptbarcode/wiki/GS1-QR-Code) don't mention the need for includetext.

Yet, if I force `includetext: false` then the error goes away. But this didn't used to be the case... Is something wrong with my installation?

**Comment by metafloor** [comment] 2022-12-10 21:10
This appears to be a regression with the 3.2.x release.  New BWIPP option checking functionality was added in recent releases and the latest release of bwip-js is the first to include it.  I will try to get a better understanding of what is happening.

**Comment by semireg** [comment] 2022-12-10 21:16
Thanks @metafloor. No problem here, just thought I'd kick the wheels a bit. 😄

**Comment by metafloor** [comment] 2022-12-11 00:31
What bwip-js module are you using (browser, browser-esm, nodejs, nodejs-esm)?  I cannot reproduce the issue.  (And both qrcode and datamatrix are well covered in the project's test framework...).  Can you provide a complete example that causes the issue?

**Comment by semireg** [comment] 2022-12-11 01:38
It's electron 19.1.7 which is Node v16.14.2. I'm using via `import bwipjs from 'bwip-js'` and then toCanvas() in a project with webpack 5.68.0 and babel 7.17.5.

**Comment by semireg** [comment] 2022-12-11 02:00
Correction. This is not node. I’m using it in the chromium instance so browser. Sorry for the confusion. Electron is confusing. On Dec 10, 2022, at 6:32 PM, metafloor ***@***.***> wrote:﻿
What bwip-js module are you using (browser, browser-esm, nodejs, nodejs-esm)?  I cannot reproduce the issue.  (And both qrcode and datamatrix are well covered in the project's test framework...).  Can you provide a complete example that causes the issue?

**Comment by metafloor** [comment] 2022-12-11 02:16
It appears webpack is performing dead code elimination that removes the initialization of the option values.  The postscript code first initializes all possible option values as local function variables to set their corresponding types.  Then compares the values in the options object to the local values to ensure they are the same data type.  You will need to explore how to prevent webpack from removing the initialization logic.

If this becomes an issue with multiple users, the type checking will need to be commented out.  But at this current time, I would like to see if this is an issue for others....

**Comment by semireg** [comment] 2022-12-11 05:04
I tried every release from 2.0.11 and it breaks at 3.2.0. When I add 'bwip-js' to webpack externals it always imports the node version (lacking toCanvas), even though my webpack target is set to electron-renderer. These might be two unreleated issues, but thought I'd mention it.

**Comment by metafloor** [comment] 2022-12-11 16:17
The current javascript ecosystem is a mess when it comes to distributing a package.  These are the current export definitions in bwip-js' `package.json`:

```
  "main": "./dist/bwip-js-node.js",
  "browser": "./dist/bwip-js.js",
  "exports": {
      "browser": {
          "import":  "./dist/bwip-js.mjs",
          "require": "./dist/bwip-js.js",
          "script":  "./dist/bwip-js-min.js"
      },
      "electron": "./dist/bwip-js-node.js",
      "node": {
          "import":  "./dist/bwip-js-node.mjs",
          "require": "./dist/bwip-js-node.js"
      }
  },
  "react-native": "./dist/bwip-js-rn.mjs",
```

Note the `electron` target is essentially nodejs.  Do you know of a better way to provide the target(s) for electron (nodejs vs browser)?

**Comment by metafloor** [comment] 2022-12-11 16:32
Found it in the [webpack documentation](https://webpack.js.org/guides/package-exports/#providing-nodejs-browser-and-electron-versions).  Please modify your local copy of `bwip-js/package.json` and replace the existing `electron` export with:

```
"exports" : {
    ...
    "electron": {
      "node": "./dist/bwip-js-node.js",
      "default": "./dist/bwip-js.js"
    },
    ....
},
```

And let me know if that works for you.

**Comment by semireg** [comment] 2022-12-11 16:48
It's really a miracle anything works at all. Kudos to supporting it up to this point. If we all end up at a barcode conference someday we can commiserate at the hotel bar. 🍻 

I tried to manually adjust these last night and didn't have much luck. Here's what I've got and the results in the chromium console.

Webpack: `target: 'electron-renderer',` .... `externals: ['bwip-js' ...`

Local bwip-js/package.json:

```
  "exports": {
    "browser": {
      "import": "./dist/bwip-js.mjs",
      "require": "./dist/bwip-js.js",
      "script": "./dist/bwip-js-min.js"
    },
    "electron": {
      "node": "./dist/bwip-js-node.js",
      "default": "./dist/bwip-js.js"
    },
    "node": {
      "import": "./dist/bwip-js-node.mjs",
      "require": "./dist/bwip-js-node.js"
    }
  },
```

App's barcode code:

```
import bwipjs from 'bwip-js';
...
console.log(`bwipjs keys: ${JSON.stringify(Object.keys(bwipjs), null, 3)}`);
console.log(`bwipjs: ${JSON.stringify(bwipjs, null, 3)}`);
```

Console:
```
bwipjs keys: [
   "request",
   "toBuffer",
   "render",
   "raw",
   "fixupOptions",
   "loadFont",
   "BWIPJS_VERSION",
   "BWIPP_VERSION",
   "BWIPJS",
   "STBTT",
   "FontLib",
   "DrawingBuiltin",
   "DrawingZlibPng"
]
barcode-handler.js:21 bwipjs: {
   "BWIPJS_VERSION": "3.2.1 (2022-12-07)",
   "BWIPP_VERSION": "2022-10-19",
   "STBTT": {},
   "FontLib": {}
}
```

Which eventually results in:

```
barcodePromise error:bwip_js__WEBPACK_IMPORTED_MODULE_2___default(...).toCanvas is not a function
```

If I remove the external tag, I then get the original reported behavior of `not a realtype/booleantype`. 🤔

**Comment by metafloor** [comment] 2022-12-11 18:22
I created a simple webpack project and was able to prove my suspicions about the dead code optimizations.  Webpack removes a considerable amount of the initialization code that the BWIPP type checking relies on.  Basically, anything not referenced by the encoder (but is used by the rendering function), is eliminated.  

So based on your latest explanation, we are facing two issues:

1. webpack broken dead code elimination.
2. electron (not webpack since you are setting the package external) not using the correct export target.

Hopefully I can get one of those fixed in the coming days.

**Comment by semireg** [comment] 2022-12-11 19:13
Perhaps 3.2 has side effects that need to be annotated or declared. https://webpack.js.org/guides/tree-shaking/#clarifying-tree-shaking-and-sideeffectsOn Dec 11, 2022, at 12:23 PM, metafloor ***@***.***> wrote:﻿
I created a simple webpack project and was able to prove my suspicions about the dead code optimizations.  Webpack removes a considerable amount of the initialization code that the BWIPP type checking relies on.  Basically, anything not referenced by the encoder (but is used by the rendering function), is eliminated.
So based on your latest explanation, we are facing two issues:

webpack broken dead code elimination.
electron (not webpack since you are setting the package external) not using the correct export target.

Hopefully I can get one of those fixed in the coming days.

**Comment by metafloor** [comment] 2022-12-12 01:24
Version 3.2.2 relaxes the rules for what a boolean value can be in the options object, making it more in line with the ethos of javascript's truthy-ness.  This doesn't address the webpack issue, or electron using the wrong module, but hopefully will allow your code to work again.

**Closed** 2023-08-04 16:36 UTC
