### ISSUE TITLE
Freetype.js is catching all uncaught exceptions

### ISSUE THREAD

**Issue by knightcode** [metafloor/bwip-js#44] opened 2016-08-15 14:19 UTC
cut it out

**Comment by waelrammo** [comment] 2016-08-23 10:08
for the love of God, +100

**Comment by metafloor** [comment] 2016-08-23 13:45
If this is such an important issue to you, then properly explain the problem and provide some code that reproduces it.  Border line rude, half sentences are not worth my time to respond to.

**Comment by waelrammo** [comment] 2016-08-23 13:50
Hey,

Sorry, it wasn't my intention to sound rude..

Essentially your file, freetype.js, contains the following code:

process["on"]("uncaughtException",(function(ex){if(!(ex instanceof
ExitStatus)){throw ex}}))

Which is overriding my own process.on('uncaughtException').

So I'm not able to handle the uncaughtExceptions (such as sending out mail
notifications) because of it.

In the meantime I've deleted that line from your freetype.js file.

Hope that's clear!

Wael

**Comment by metafloor** [comment] 2016-08-23 14:07
freetype.js is compiled using emscripten, and the culprit line is part of emscripten's standard framework.  That certainly doesn't play well with other modules.

I think commenting out the line will be the only solution, at least for the interim.  The way bwip-js uses freetype, that bit of code is useless as we don't exit from the emscripten environment. 

The best solution may be to add a step to the bwip-js build script that comments out that bit of code.  I will look into that later this week when I have some spare time.

**Comment by pmcnr-hx** [comment] 2016-09-19 13:15
👍Thank you for the wonderful work that is `bwip-js`! If you fix this very minor blemish, it will be even more amazing.

**Comment by pmcnr-hx** [comment] 2016-09-19 15:54
`v1.1.1` fixes the issue for me @metafloor. Thanks for super quick fix! 👍

**Comment by metafloor** [comment] 2016-09-20 16:02
I am closing this issue.  If it is still is a problem for anyone else, please open a new issue.

**Closed by metafloor** 2016-09-20 16:02 UTC
