### ISSUE TITLE
 Cannot read property 'NaN' of undefined

### ISSUE THREAD

**Issue by dadaa1** [metafloor/bwip-js#120] opened 2018-11-29 01:59 UTC
In my react application, there is a problem: call the bwipjs function many times, there will be the above error.
![image](https://user-images.githubusercontent.com/12947361/49194183-1155bc00-f3bd-11e8-91a1-c6e851311bc7.png)
this is code ：
![image](https://user-images.githubusercontent.com/12947361/49194214-2f232100-f3bd-11e8-8de8-d5b7b48486ab.png)
I thought it was the same id, but I changed it to a random string, or there was a mistake.

**Comment by dadaa1** [comment] 2018-11-29 02:01
Only the first one can render normally,Everything else will make a mistake.

**Comment by asela-wijesinghe** [comment] 2019-02-01 12:32
same issue. @dadaa1 u got any solutions?

**Comment by metafloor** [comment] 2019-02-01 16:38
There is no way for me to understand what is going on with posts like this.  In general, if you want assistance with an issue, you need to distill the problem down to a minimal working example that can be reproduced.

**Comment by asela-wijesinghe** [comment] 2019-02-01 17:14
I think i had my issue sorted after hosting the application and i believe it has somethng to do with the local application eventhough i don't quite understand why it is.But its ok from me to close the issue if the creator of the issue is satisfied

**Comment by metafloor** [comment] 2019-02-01 17:43
My guess would be a timing issue.  Local apps with GETs to a local server complete much faster.  Slower GETs may allow initialization code to complete.  I am aware of some global state in the browser version of the font library that can potentially race when multiple bar codes are rendering simultaneously (async).

**Comment by dadaa1** [comment] 2019-02-02 09:15
@asela-wijesinghe  My solution is：Not using bwipjs fonts，Instead, a div is used to place text。

**Comment by metafloor** [comment] 2019-12-10 18:01
This should be resolved in the 2.0 release as font loading is no longer async (node.js and the browser) the browser code is fully async.

**Closed by metafloor** 2019-12-10 18:01 UTC
