### ISSUE TITLE
GS1 Datamatrix generation freeze

### ISSUE THREAD

**Issue by ziroow** [metafloor/bwip-js#148] opened 2020-01-15 15:59 UTC
If you try to generate gs1datamatrix with the following data `(01)02900001333399212v<t!6SWsA/KE^02991012A^0299296T7YI2b9zPMt8y9mU+m7wSUbpe6+7rMdHyo5MMd5h08V1skespIRxR1NUp3MjLP1qDnJikugL76w1Yktr+lHw==` in [PostScript online demo](https://the-burtons.xyz/barcode-generator/) – it works fine. But if you use the same data in the [JS online demo](http://bwip-js.metafloor.com/demo/demo.html), it freezes.

If you change the 29'th character in the original data to an uppercase letter: `(01)02900001333399212v<t!6SWSA/KE^02991012A^0299296T7YI2b9zPMt8y9mU+m7wSUbpe6+7rMdHyo5MMd5h08V1skespIRxR1NUp3MjLP1qDnJikugL76w1Yktr+lHw==` then gs1datamatrix is successfully generated in the [JS online demo](http://bwip-js.metafloor.com/demo/demo.html).

Freezes are also reproduced locally in [all examples](https://github.com/metafloor/bwip-js/tree/v2.0.5/examples), if you use the original data. And it works fine if use the changed data.

**Comment by metafloor** [comment] 2020-01-15 22:03
Interesting.  Is the S/s difference a flag that switches the encoding behavior?

**Comment by ziroow** [comment] 2020-01-16 10:59
I don't know. But changing «S/s» to «Q/q» or any other letter will give the same result.

Bad: `(01)02900001333399212v<t!6SWqA/KE^02991012A^0299296T7YI2b9zPMt8y9mU+m7wSUbpe6+7rMdHyo5MMd5h08V1skespIRxR1NUp3MjLP1qDnJikugL76w1Yktr+lHw==`
Good: `(01)02900001333399212v<t!6SWQA/KE^02991012A^0299296T7YI2b9zPMt8y9mU+m7wSUbpe6+7rMdHyo5MMd5h08V1skespIRxR1NUp3MjLP1qDnJikugL76w1Yktr+lHw==`

**Comment by terryburton** [comment] 2020-01-16 14:54
Aside from BWIP-JS malfunctioning...

@ziroow: I note that your input to `gs1datamatrix` is malformed. `gs1datamatrix` takes care of the GS1-syntax data encoding for you so you need only enter an "(AI)value(AI)value" string, not need to insert `FNC1` characters. Even so, your input looks wrong. What is the GS1 data that you are trying to represent?

(Adise: Generally speaking when manually encoding GS1-syntax you should not substitute FNC1 characters with ASCII "GS".)

**Comment by metafloor** [comment] 2020-01-16 15:51
@terryburton: I am pretty sure this is a bwip-js cross-compile issue.  During the codeword encoding phase, it goes wrong.  Still trying to figure out why a lower-case vs upper-case is causing a difference.

**Comment by ziroow** [comment] 2020-01-17 10:13
@terryburton: I have strict requirements for the format of the encoded data. The data must match the pattern `{FNC1}01value21value{GS}91value{GS}92value`. The separator should be exactly 29 ASCII code. Unfortunately, I didn't find in the documentation how to replace the delimiter character from {FNC1} to {GS}.

@metafloor: After reading the source code, I saw that in function `lookup` there is a branch for parameter `mailmark` with value `C40`. Passing this parameter helps to generate a symbol without freezes. But I'm not sure if this way is correct.

**Comment by terryburton** [comment] 2020-01-17 10:24
On Fri, 17 Jan 2020, 10:13 Andrey Alexandrov, <notifications@github.com>
wrote:

> @terryburton <https://github.com/terryburton>: I have strict requirements
> for the format of the encoded data. The data must match the pattern
> {FNC1}01value21value{GS}91value{GS}92value. The separator should be
> exactly 29 ASCII code. Unfortunately, I didn't find in the documentation
> how to replace the delimiter character from {FNC1} to {GS}.
>
> In that case you should pass the data to the gs1datamatrix helper encoder
as "(01)value(21)value(91)value(92)value".

The library will do the right thing with the leading FNC1 and the FNC1 that
terminates the variable-length fields.

Alternatively use the datamatrix encoder directly and do the encoding
manually with using the parsefnc option, but make sure you use FNC1 not GS
for the separator. Consult the GS1 General Specifications as to why this is
the case.

**Comment by metafloor** [comment] 2020-01-18 04:00
It took some painful debugging (the bug causes an infinite loop which the chrome/firefox debug tools do not handle well) but finally tracked it down.  It is caused by a difference in the result of floating point division due to postscript's single-precision versus javascript's double-precision.  Here is a capture of what is happening:

![image](https://user-images.githubusercontent.com/385436/72658075-331b5500-3969-11ea-9a3f-88ad51f921df.png)

That 12.999999999999996 is being tested against 13.  If using single-precision floats, the value would have rounded to 13 and compared correctly.  

Hopefully, the fix won't hit performance too hard.  Any time the postscript code divides (`div` operator), the equivalent javascript code must do an expensive rounding operation to emulate single-precision.

I should have a new release ready by early next week.

**Comment by metafloor** [comment] 2020-01-22 01:55
Hi @terryburton, hoping you are still following this thread.  Can I ask you for some insight into the datamatrix encoder?  

The problem I am seeing is that the codeword optimization seems really sensitive to floating point rounding errors.  I fix the rounding issues for one test case and it breaks in another.  Is there any postscript floating point behavior (aside from single-precision) that differs from standard FP behavior in say C/C++?  I have perused the "red book" but haven't seen anything out of the norm...

Thanks.

**Comment by terryburton** [comment] 2020-01-22 11:34
I've seen variation between PS VM implementations of FP, especially in roundoff after division.

So a couple of points:

The datamatrix encoder should be fixed to not loop in pathological cases. I consider that doing so is a bug in BWIPP and that it is much better to fail gracefully by just generating a less optimal encoding.

In general, there's not actually any need to use floating point calculations in any barcode encoding that I'm aware of. (With the exception of the LDPC encoding used in JAB Code, but hopefully that will change so that RSEC is an alternative, before the specification is finalised. LDPC at the block sizes used in the current specification is far too expensive for PS VMs since it requires >100,000,000 iterations of some innermost loop.)

When I find time I'll take a look at what is required to remove the FP arithmetic from datamatrix. The code is implementing the "look-ahead test" given in _Annex S  - Encoding Data Using the Minimum Symbol Data Characters for ECC 200_ of ISO/IEC 16022. The same process can be implemented with rationals so that roundoff does not play a part.

**Comment by metafloor** [comment] 2020-01-23 18:01
Terry, thanks for the reply.  I look forward to a non-FP solution to the optimization pass.  For the time being, I have manually "constant folded" the `div` expressions in the two datamatrix encoders so the values are truncated to their single-precision equivalents.  This was the least invasive, least breaking fix for the issue.

@ziroow: Release 2.0.6 is available on github and npm with the fix.  I will be updating the public API this weekend (it is still running 1.7.4).

**Closed** 2022-12-06 23:52 UTC
