### ISSUE TITLE
Question - Multiple barcodes

### ISSUE THREAD

**Issue by cheeroke** [metafloor/bwip-js#101] opened 2018-02-01 14:31 UTC
Hi, I found this repo very usefull, but was wondering, is it possible to generate more than one barcode? As of now every new is replacing previous i would like to generate more and than export it. Can you possibly lead me where i should change code to achieve this - if possible?
Thanks in advance.

**Comment by metafloor** [comment] 2018-02-01 15:23
Are you using the public API or hosting the module on your own server or running in a browser?

Each call into bwip-js returns one barcode.  But you can call it as many times as needed.  Please give an example of what you are trying to do so I can provide better help.

**Comment by cheeroke** [comment] 2018-02-02 08:50
I've downloaded bwip-js-master and I am running in a browser ( as i failed to run on my own server which in future would be preferable).
 
My aim is to be able to create say up to 10 barcodes on one page and than print them on one sheet A4.
So every time i fill in data for barcode I would like, by pressing "Show Barcode" to generate new Aztec code next to previous and than "Save as.." or add extra button to generate page with all barcodes and be able to print it.

Thanks

**Comment by metafloor** [comment] 2018-02-02 13:14
Sounds like you are using the demo.  That is designed only for testing barcode generation and the effects of each symbol's options.  It is not meant for production.

You need to embed the barcodes in an html file, using <img> elements, and set their source to either the public API or to a local node.js running server.js that is included in the distribution.

Alternatively, you can host bwip-js in the browser (using vanilla html and javascript or a framework such as React) and render the barcodes to canvas elements (similar to how the demo works). 

Please look over the project's readme/home page to understand how to implement this.

**Comment by champunes** [comment] 2018-02-06 16:14
I've got an issue trying to put multiple React components with a barcode inside them. The problem seems to be the concurrent call of bwipjs function. If I call bwipjs before another call has ended, bwipjs returns the following error: 

`TypeError: Cannot read property 'NaN' of undefined
    at Array.<anonymous> (bwipjs.js:433)
    at BWIPJS.render (bwipjs.js:599)
    at browser-bwipjs.js:116
    at Object.loadfonts (browser-fonts.js:106)
    at toCanvas (browser-bwipjs.js:112)
    at ReceiptBarcode.renderBarcode (receipt_text.jsx:56)
    at ReceiptBarcode.componentDidMount (receipt_text.jsx:25)
    at ReactCompositeComponent.js:262
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponent.js:261`

I've tried setting a timeout in one of the React components for waiting some time before calling bwipjs, and it works nicely. I'm not sure, but it looks like bwipjs is using something that do not support concurrent calls.

In my case, I'm calling the funcion with different canvas ids and the same barcode code.

**Comment by metafloor** [comment] 2018-02-06 16:33
I suspect you are re-using the same bwip-js instance for the concurrent calls.  You can only re-use a bwip-js instance after it has completed.

**Comment by champunes** [comment] 2018-02-06 16:42
I'm using browserify for making a bundle of all my React App, so, there's only a require and it's the same instance. I suppose that I need to store a instance for each 'BarcodeComponent', o make the calls to bwipjs sequentially.

**Comment by metafloor** [comment] 2018-02-06 16:58
Just looked over the code and it is the font-lib that is the cause of the issue.  There is some global state (cache) that does not play well with concurrent calls.  For the time being, you will need to serialize access.

This will be fixed in the upcoming 2.0 release, but I have just begun work on it and do not have a target release date yet.

**Comment by KaMeHb-UA** [comment] 2018-11-05 17:09
@cheeroke, @champunes
I know, this is not a parallel way, but if you want multiple barcodes, there is way to do this (I wrote this module wrapper for own purposes, so you may want to do some similar, not the same):
```javascript
import bwipjs from 'bwip-js'

const callStack = [];

function next(){
    const { cb, canvas, type, text } = callStack[0];
    bwipjs(canvas, {
        bcid:        type,
        text,
        scale:       5,
        height:      10,
        includetext: true,
        textxalign:  'center',
    }, (err, cvs) => {
        if(err) cb(err); else cb(null, cvs);
        callStack.shift();
        if(callStack.length) next()
    })
}

function registerNewCallback(cb, canvas, type, text){
    callStack.push({cb, canvas, type, text});
    if(callStack.length == 1) next()
}

export default (
    /**
     * @arg {string | HTMLCanvasElement} canvas
     * @arg {string} type
     * @arg {string} text
     * @return {Promise<HTMLCanvasElement>}
     */
    (canvas, type, text) => {
        return new Promise((resolve, reject) => {
            registerNewCallback((err, cvs) => {
                if(err) reject(err); else resolve(cvs)
            }, canvas, type, text)
        })
    }
)
```

**Comment by metafloor** [comment] 2019-12-10 18:10
Async issues in the browser are gone in the 2.0 release.  Code is fully synchronous when drawing to canvas.

**Closed by metafloor** 2019-12-10 18:10 UTC
