### ISSUE TITLE
GS1 DataBar Expanded Stacked freezes browser

### ISSUE THREAD

**Issue by pecko** [metafloor/bwip-js#189] opened 2020-12-13 16:25 UTC
Steps to reproduce:
- open http://bwip-js.metafloor.com/demo/demo.html
- enter the following values:
Barcde Type: GS1 Databar Expanded Stacked
Bar Text: (01)00628176379104(17)500723(10)103
Alt Text: (01)00628176379104(17)500723(10)103
Options: segments=3
- click Show Barcode

or click [bwip-js freezes](https://bwipjs-api.metafloor.com/?bcid=databarexpandedstacked&text=(01)00628176379104(17)500723(10)103&alttext=(01)00628176379104(17)500723(10)103&segments=3&scale=2)

Browser freezes.

**Comment by metafloor** [comment] 2020-12-13 19:03
@terryburton:  Can you take a look at this one? 

I believe the issue is in the edge tracing done in `renmatrix` but the bwip-js translation is masking exactly what is wrong.

ghostscript errs out on a `getinterval`.  The javascript code just goes into an infinite loop until it runs out of memory building an array.

Thanks!

**Comment by terryburton** [comment] 2020-12-13 20:12
`segments` must be even. The failure case isn't caught and results in a pixs array that is not correct for the symbol dimensions.

I'll add error handling to catch that.

**Comment by terryburton** [comment] 2020-12-13 21:55
The error handling will be in the next release: https://github.com/bwipp/postscriptbarcode/commit/bd4fdc0d07de6dad22dc250920b91c2f189b8e61

**Comment by metafloor** [comment] 2020-12-14 15:04
Thanks Terry!

**Comment by metafloor** [comment] 2021-02-05 16:16
Fixed in the current release 2.0.12.

**Closed by metafloor** 2021-02-05 16:16 UTC
