### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by koenm** [metafloor/bwip-js#167] opened 2020-07-08 08:13 UTC
Hi guys,

using the API i'm getting a TypeError:
TypeError: Cannot set property 'prev' of null

The problem is occurring since this morning. Before it always worked like a charm.

Anyone has a clue?
Thanks

**Comment by metafloor** [comment] 2020-07-08 13:12
Please provide an example that reproduces the error.

**Comment by koenm** [comment] 2020-07-08 13:15
Hi,

it's also in the example on your webpage:

http://bwipjs-api.metafloor.com/?bcid=code128&text=AB1234567890&scale=3&rotate=I&includetext

**Comment by metafloor** [comment] 2020-07-08 13:22
It's a problem with the glyph cache.  I have restarted the api server, which clears the cache, and it is working again. 

Will continue to look into it.

**Comment by metafloor** [comment] 2020-07-08 14:13
The API server has been updated with the fix and restarted.

**Comment by metafloor** [comment] 2020-07-08 20:42
Since no new complaints, closing this issue.

**Closed by metafloor** 2020-07-08 20:42 UTC
