### ISSUE TITLE
Prevent change size of text in code 128

### ISSUE THREAD

**Issue by dannyto** [metafloor/bwip-js#41] opened 2016-06-24 07:02 UTC
Hi there,

 Is any options that I can prevent change the size of text when I change width of code 128.

Thankz!

**Comment by metafloor** [comment] 2016-06-27 23:47
By *change width*, do you mean changing the scaling factor?  In BWIPP, text size is constant regardless of the length of the barcode text.  

Please give me an example of what you are trying to do.

**Comment by efrainx3** [comment] 2016-06-28 16:01
Hello,
I want to change the size of the numbers that are under the barcode. I'm using the GS1-128 standar.
![barcodegs1_128](https://cloud.githubusercontent.com/assets/15133372/16422850/72ea74d0-3d1f-11e6-9e12-ff5b4e917016.png)
Thank you very much for your help.

**Comment by metafloor** [comment] 2016-06-28 16:22
Ok, that is easy to do.  Here are the defaults for *gs1-128* (pulled directly from `barcode.ps` included in the bwip-js dist):

```
    /includetext false def    % Enable/disable text
    /textfont /Courier def
    /textsize 10 def
    /textxoffset 0 def
    /textyoffset -7 def
    /height 0.5 def
    /linkagea false def
    /linkagec false def
```

N.B.  bwip-js overrides the Courier and Helvetica font names for the barcode text, always using OCR-B but keeps the original font size (except for the ISBN/ISMN/ISSN extra text which get changed from 9pt to 8.5pt and use the OCR-A font).

So you want to use the `textsize` option, specifying a smaller point size.  I would start with `textsize=9` and then adjust as necessary.

**Comment by metafloor** [comment] 2016-06-28 16:29
Just occurred to me that it would be better to reference `bwipp.js` code in my responses, that way I can make changes to default values and not have to remember what was changed....  Here is the same code from `bwipp.js`:

```javascript
    $0["gs1-128"] = function() {
        /*...snip...*/
        $1.includetext = false; /*2932*/
        $1.textfont = "Courier"; /*2933*/
        $1.textsize = 10; /*2934*/
        $1.textxoffset = 0; /*2935*/
        $1.textyoffset = -8.5; /*2936*/
        $1.height = 0.5; /*2937*/
        $1.linkagea = false; /*2938*/
        $1.linkagec = false; /*2939*/
```

The comments to the right of each line reference the source line number in `barcode.ps`.

**Comment by efrainx3** [comment] 2016-06-28 16:37
Excellent. That was the answer I was looking for. Thank you very much :) :+1:

**Comment by metafloor** [comment] 2016-06-29 01:22
@dannyto Does this answer your question as well?  If so, please close the issue.  Thx.

**Comment by dannyto** [comment] 2016-06-29 06:38
No, my case is different.
When I change width option, text is scaling

With option: width=3 textsize=10
![gs1-128--01-95012345678903-3103-000123](https://cloud.githubusercontent.com/assets/13778373/16442636/22bbac56-3dfe-11e6-8991-e03ee10c6c91.png)

With option: width=5 textsize=10
![gs1-128--01-95012345678903-3103-000123 1](https://cloud.githubusercontent.com/assets/13778373/16442649/3edbb840-3dfe-11e6-8e54-bbc0609a576f.png)

I want text will not scale when change changing the width of barcode
Thank you for your help

**Comment by metafloor** [comment] 2016-06-30 15:03
I made some tests and understand what is happening.  The font is scaling correctly.  The text is drawn to a width of 5in.  The problem is with the barcode.  Barcodes do not scale linearly - they scale in quantums.  A narrow element can only be a fixed number of pixels.  Likewise, a 2x element can only be twice the width of the narrow element; and so on.  (code128 uses 1x, 2x, 3x, and 4x element widths.)  When you change the width of the narrow element, the entire barcode "jumps" in width by all of the 1x, 2x, 3x, and 4x multiples.

So this behavior is by design (otherwise the barcode element widths would be out of tolerance) and there is nothing to fix.  The best you can do is adjust the font size to account for the barcode not scaling linearly.

**Closed** 2017-05-24 21:17 UTC
