### ISSUE TITLE
the quality of result png is not right for a gs1-128 barcode

### ISSUE THREAD

**Issue by leafred** [metafloor/bwip-js#22] opened 2016-01-07 23:23 UTC
I tried this:
 http://api-bwipjs.rhcloud.com/?bcid=gs1-128&text=(019931265099999891SHW400000101000600206)&scaleX=1&scaleY=2

I also used my own nodejs in ubuntu server, got the same result.

I printed the barcode, the quality is poor in thermal printer, cannot be scanned, Is there anything to be configured?

Thanks.

**Comment by terryburton** [comment] 2016-01-08 11:36
The library takes care of encoding the data into GS1 Application Identifier standard format so you should provide the input with the brackets around the AIs, as follows:

(01)99312650999998(91)SHW400000101000600206

**Comment by leafred** [comment] 2016-01-08 20:32
Thanks for your reply, this is good point for me, however the quality I mentioned is that the PNG barcode image is too rough in printing, I tried to convert it to JPG, then it solved the problem. I don' t know the reason.

**Comment by metafloor** [comment] 2016-01-09 01:15
PNG is a lossless image format whereas JPEG is lossy, so the image format is most likely not the cause.  Are you using a browser for printing?  Or some other 3rd party software that might understand the JPEG format better than PNG?  Are you setting the size of the image when printing or letting it default to the image's native size?

**Comment by leafred** [comment] 2016-01-09 04:56
I did not resize the image, used php tcpdf to insert barcode image as a part of PDF shipping label. I also tried print from Chrome browser, the result is the same.

**Comment by leafred** [comment] 2016-01-09 08:44
I realised it happened in Chrome browser, there is no problem if I save the pdf to computer disk then open with pdf reader and print in Windows. For our case we have to print in Chrome, bswip-is is very good indeed, it is not perfect for us as we have to convert png to jpg.

**Comment by metafloor** [comment] 2016-06-17 16:21
Closing this issue as I believe it is resolved.

**Closed by metafloor** 2016-06-17 16:21 UTC
