### ISSUE TITLE
Brace added after semicolon in datamatrix

### ISSUE THREAD

**Issue by oscarwroche** [metafloor/bwip-js#93] opened 2017-10-17 12:48 UTC
I'm trying to encode the following string as a Datamatrix : "1;FDJ;PDJ;17456,2355;43;C;649P3,652P3,100P3;50" - whenever I'm trying to decode the generated Datamatrix the output is "1;FDJ;PDJ;17456,2355;43;C;649P3,652P3,100P3;{50" with an added brace after the last semicolon.
This doesn't happen if add or remove one character to the input string or if I replace the last semicolon by a standard alphanumeric character, but still happens if I replace the last semicolon with another non-alphanumeric character (i.e. '.', ',' ,'/').
Any clue as to why this is happening ? This happens with both the API and Online Demo.

**Comment by metafloor** [comment] 2017-10-17 13:26
Please test the string on the original PostScript version of the code:

https://the-burtons.xyz/barcode-generator/

I am offsite right now and do not have access to a 2d scanner, otherwise I would check it myself.

**Comment by metafloor** [comment] 2017-10-17 16:34
@terryburton: Hi Terry, I believe this may be an upstream issue.  Using an image from the BWIPP online generator, zxing is finding the extra curly as well.  Can you take a look?  Thanks.

**Comment by terryburton** [comment] 2017-10-17 21:02
I've got to the bottom of this and believe that I've fixed it in this branch:

https://github.com/bwipp/postscriptbarcode/tree/datamatrix-fix

There is an end of data condition when in EDIFACT encoding that states that when you can fill the last one or two codewords of a symbol's data region (such that no padding is required) then you should *implicitly* latch back to ASCII and do so. This logic was being short circuited by the code that determines the optimal mode which was *explicitly* latching to ASCII for the final characters, introducing the erroneous character.

I found another related issue that I believe I have resolved (due to me misinterpreting the spec) but I haven't thoroughly tested it so I'll merge into trunk once I have time.

The Online Barcode generator has been synced with this branch. Since I haven't bumped the version, if you regenerate the same symbol be sure to add some random data to options field to foil the cache.

**Comment by metafloor** [comment] 2017-10-17 22:32
@oscarwroche: Attached is a new bwipp.js file that includes the fix Terry just published.  Copy to your local `node_modules\bwip-js\bwipp.js` and please test.  Once verified, I will push the fix into a formal release. 

[bwipp.js.zip](https://github.com/metafloor/bwip-js/files/1392829/bwipp.js.zip)

**Comment by oscarwroche** [comment] 2017-10-18 08:28
Many thanks for your reactivity. I've downloaded the file and copied it to my local modules - the problematic string is now decoded without the added character !

**Comment by oscarwroche** [comment] 2017-10-18 08:41
I just tried the same string, but with only one digit at the end "1;FDJ;PDJ;17456,2355;43;C;649P3,652P3,100P3;5" and it is decoded as "1;FDJ;PDJ;17456,2355;43;C;649P3,652P3,100P3;83", in the same way "1;FDJ;PDJ;17456,2355;43;C;649P3,652P3,100P3;2" is decoded as "1;FDJ;PDJ;17456,2355;43;C;649P3,652P3,100P3;71" - this doesn't happen with the previous version.

**Comment by terryburton** [comment] 2017-10-18 21:29
Tricky... I think the issues are now fixed in the master branch.

@metafloor If you could please transpile it for testing. If it checks out then I'll tag a release.

The issue is that the specification is vague about how to handle all of the end of data conditions for encodings ending in EDIFACT mode:

> If EDIFACT Encodation is in effect at the end of the symbol before the first error correction character, and only one or two codewords remain after the last EDIFACT codeword triplet, these remaining codewords shall be encoded in ASCII Encodation without requiring an Unlatch character.

I read this as saying to put two find symbol characters (from input data) into two final codewords as ASCII and to put one final symbol character into one final codeword as ASCII. It not clear what to do with one final symbol character when two codewords remain, or indeed when there are no final symbol characters and one or two codewords remain - I was unlatching to ASCII.

It turns out that fewer than three codewords at the end of data are always interpreted as ASCII (implicit latch) so we just use ASCII and pad whatever remains. As is often the case for a specification, it is full of "truisms" (often ambiguous) rather than telling you step by step what to do.

**Comment by metafloor** [comment] 2017-10-18 22:07
@terryburton : Thanks for all the work.  These corner cases can be tricky!

@oscarwroche :  The latest version of bwipp.js is attached.  Same procedure as before.

[bwipp.js.zip](https://github.com/metafloor/bwip-js/files/1396495/bwipp.js.zip)

**Comment by oscarwroche** [comment] 2017-10-19 09:47
Just tried it and both cases seem to be working fine now. Thanks again to both of you for your work !! it allowed me to learn a lot about encoding too :)

**Comment by terryburton** [comment] 2017-10-19 11:19
BWIPP release 2017-10-19 tagged:

https://github.com/bwipp/postscriptbarcode/releases/tag/2017-10-19

**Comment by p2k** [comment] 2018-02-15 10:21
Just for further reference, here are some more strings that would have produced the error (this time the brace is appended at the end):
`INHTH+Eg4m0S!Z]<ytM7a[TC<UpOt3Nn}B;p++5[N)HH`
`INHTe=cozA>&DED_mhUQPJ12=zGbd2SRbv5iH3I;Y-VC`
`INHT3h7JP3DgV=CcfMt%(0+UimssHPJk*U;cX::UN&,*`

@metafloor Can you please make a release for bwip-js that incorporates the latest changes? With the current master I still get the braces, both with my strings and the thread opener's string. They all work fine on https://the-burtons.xyz/barcode-generator/

**Comment by metafloor** [comment] 2018-02-15 16:53
Just released version 1.6.3 (BWIPP 2018-02-04).  Verified that the above strings were mis-encoded in 1.6.2 and correctly in 1.6.3.

**Closed** 2018-02-16 16:58 UTC
